stages:
  - test

.unit-test: &unit
  stage: test
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  script:
    - tox --skip-missing-interpreters -- -qqrf
  before_script:
    - python -V
    - pip install tox
    - pip install -e .
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

test-python36:
  <<: *unit
  image: python:3.6
  variables:
    TOXENV: py36

test-python37:
  <<: *unit
  image: python:3.7
  variables:
  script:
    - tox --skip-missing-interpreters -p auto -- -rf

test-python38:
  <<: *unit
  image: python:3.8
  variables:
    TOXENV: py38

test-python39:
  <<: *unit
  image: python:3.9
  variables:
    TOXENV: py39

test-python310:
  <<: *unit
  image: python:3.10
  variables:
    TOXENV: py310

test-pypy3:
  <<: *unit
  image: pypy:3
  variables:
    TOXENV: pypy3

test-coverage:
  <<: *unit
  image: python:3.7
  script:
    - export GIT_ID=$(hg tip --template '{node}\n')
    - export GIT_AUTHOR_NAME=$(hg tip --template '{author|person}\n')
    - export GIT_AUTHOR_EMAIL=$(hg tip --template '{author|email}\n')
    - export GIT_COMMITTER_NAME=$(hg tip --template '{author|person}\n')
    - export GIT_COMMITTER_EMAIL=$(hg tip --template '{author|email}\n')
    - export GIT_MESSAGE=$(hg tip --template '{desc}\n')
    - export GIT_BRANCH=$(hg branch)
    - export GIT_URL=https://foss.heptapod.net/openpyxl/openpyxl
    - tox -e cov
